name: Workflow template for CI jobs for Core Components
on:
  workflow_call:

env:
  CLICOLOR: 1
  # We run multiple binaries in parallel, and by default they will try to utilize all the
  # available CPUs. In tests, there is not much CPU-intensive work (rayon), but a lot of
  # async work (tokio), so we prioritize tokio.
  TOKIO_WORKER_THREADS: 4
  RAYON_NUM_THREADS: 2
  CARGO_TERM_COLOR: "always"
  CARGO_INCREMENTAL: "0"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  # Rust version to use.
  nightly: nightly-2024-08-01

jobs:
  lint:
    name: lint
    uses: ./.github/workflows/ci-core-lint-reusable.yml

  tests:
    runs-on: [ matterlabs-ci-runner-ultra-performance ]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          components: rustfmt, clippy
      
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Setup remaining deps
        run: |
          sudo apt-get update && sudo apt-get install pkg-config cmake clang lld libssl-dev apt-transport-https -y
          npm install -g yarn
          yarn set version 1.22.19
          cargo install sqlx-cli --version 0.8.1
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH

      - name: Build zk_toolbox
        run: bash -c "./bin/zkt"

      - name: Create log directories
        run: |
          SERVER_LOGS_DIR=logs/server
          INTEGRATION_TESTS_LOGS_DIR=logs/integration_tests
          INTEGRATION_TESTS_EN_LOGS_DIR=logs/integration_tests/en
          SNAPSHOT_RECOVERY_LOGS_DIR=logs/integration_tests/en
          GENESIS_RECOVERY_LOGS_DIR=logs/integration_tests/en
          EXTERNAL_NODE_LOGS_DIR=logs/external_node
          REVERT_LOGS_DIR=logs/revert
          
          mkdir -p $SERVER_LOGS_DIR
          mkdir -p $INTEGRATION_TESTS_LOGS_DIR
          mkdir -p $INTEGRATION_TESTS_EN_LOGS_DIR
          mkdir -p $SNAPSHOT_RECOVERY_LOGS_DIR
          mkdir -p $GENESIS_RECOVERY_LOGS_DIR
          mkdir -p $EXTERNAL_NODE_LOGS_DIR
          mkdir -p $REVERT_LOGS_DIR
          
          echo "SERVER_LOGS_DIR=$SERVER_LOGS_DIR" >> $GITHUB_ENV
          echo "INTEGRATION_TESTS_LOGS_DIR=$INTEGRATION_TESTS_LOGS_DIR" >> $GITHUB_ENV
          echo "INTEGRATION_TESTS_EN_LOGS_DIR=$INTEGRATION_TESTS_EN_LOGS_DIR" >> $GITHUB_ENV
          echo "SNAPSHOT_RECOVERY_LOGS_DIR=$SNAPSHOT_RECOVERY_LOGS_DIR" >> $GITHUB_ENV
          echo "GENESIS_RECOVERY_LOGS_DIR=$GENESIS_RECOVERY_LOGS_DIR" >> $GITHUB_ENV
          echo "EXTERNAL_NODE_LOGS_DIR=$EXTERNAL_NODE_LOGS_DIR" >> $GITHUB_ENV
          echo "REVERT_LOGS_DIR=$REVERT_LOGS_DIR" >> $GITHUB_ENV
      
      - name: Run containers
        run: |
          zk_inception containers -o false

      - name: Initialize ecosystem
        run: |
          git config --global --add safe.directory /usr/src/zksync
          git config --global --add safe.directory /usr/src/zksync/contracts/system-contracts
          git config --global --add safe.directory /usr/src/zksync/contracts

          zk_inception ecosystem init --deploy-paymaster --deploy-erc20 \
          --deploy-ecosystem --l1-rpc-url=http://localhost:8545 \
          --server-db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --server-db-name=zksync_server_localhost_era \
          --prover-db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --prover-db-name=zksync_prover_localhost_era \
          --ignore-prerequisites --verbose \
          --observability=false

      - name: Read Custom Token address and set as environment variable
        run: |
          address=$(awk -F": " '/tokens:/ {found_tokens=1} found_tokens && /DAI:/ {found_dai=1} found_dai && /address:/ {print $2; exit}' ./configs/erc20.yaml)
          echo "address=$address"
          echo "address=$address" >> $GITHUB_ENV

      - name: Create and initialize Validium chain
        run: |
          zk_inception chain create \
          --chain-name validium \
          --chain-id sequential \
          --prover-mode no-proofs \
          --wallet-creation localhost \
          --l1-batch-commit-data-generator-mode validium \
          --base-token-address 0x0000000000000000000000000000000000000001 \
          --base-token-price-nominator 1 \
          --base-token-price-denominator 1 \
          --set-as-default false \
          --ignore-prerequisites

          zk_inception chain init \
          --deploy-paymaster \
          --l1-rpc-url=http://localhost:8545 \
          --server-db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --server-db-name=zksync_server_localhost_validium \
          --prover-db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --prover-db-name=zksync_prover_localhost_validium \
          --port-offset 2000 \
          --chain validium

      - name: Create and initialize chain with Custom Token
        run: |
          zk_inception chain create \
          --chain-name custom_token \
          --chain-id sequential \
          --prover-mode no-proofs \
          --wallet-creation localhost \
          --l1-batch-commit-data-generator-mode rollup \
          --base-token-address ${{ env.address }} \
          --base-token-price-nominator 3 \
          --base-token-price-denominator 2 \
          --set-as-default false \
          --ignore-prerequisites

          zk_inception chain init \
          --deploy-paymaster \
          --l1-rpc-url=http://localhost:8545 \
          --server-db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --server-db-name=zksync_server_localhost_custom_token \
          --prover-db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --prover-db-name=zksync_prover_localhost_custom_token \
          --port-offset 3000 \
          --chain custom_token

      - name: Build test dependencies
        run: |
          zk_supervisor test build

      - name: Run servers
        run: |
          zk_inception server --ignore-prerequisites --chain era &> ${{ env.SERVER_LOGS_DIR }}/rollup.log &
          zk_inception server --ignore-prerequisites --chain validium &> ${{ env.SERVER_LOGS_DIR }}/validium.log &
          zk_inception server --ignore-prerequisites --chain custom_token &> ${{ env.SERVER_LOGS_DIR }}/custom_token.log &
          sleep 5

      - name: Run integration tests
        run: |
          zk_supervisor test integration --no-deps --ignore-prerequisites --chain era &> ${{ env.INTEGRATION_TESTS_LOGS_DIR }}/rollup.log &
          PID1=$!

          zk_supervisor test integration --no-deps --ignore-prerequisites --chain validium &> ${{ env.INTEGRATION_TESTS_LOGS_DIR }}/validium.log &
          PID2=$!

          zk_supervisor test integration --no-deps --ignore-prerequisites --chain custom_token &> ${{ env.INTEGRATION_TESTS_LOGS_DIR }}/custom_token.log &
          PID3=$!

          wait $PID1
          wait $PID2
          wait $PID3

      - name: Init external nodes
        run: |
          zk_inception external-node configs --db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --db-name=zksync_en_localhost_era_rollup --l1-rpc-url=http://localhost:8545 --chain era
          zk_inception external-node init --ignore-prerequisites --chain era 
          
          zk_inception external-node configs --db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --db-name=zksync_en_localhost_era_validium1 --l1-rpc-url=http://localhost:8545 --chain validium
          zk_inception external-node init --ignore-prerequisites --chain validium

          zk_inception external-node configs --db-url=postgres://postgres:notsecurepassword@localhost:5432 \
          --db-name=zksync_en_localhost_era_custom_token --l1-rpc-url=http://localhost:8545 --chain custom_token
          zk_inception external-node init --ignore-prerequisites --chain custom_token

      - name: Run recovery tests (from snapshot)
        run: |

          zk_supervisor test recovery --snapshot --no-deps --ignore-prerequisites --verbose --chain era &> ${{ env.SNAPSHOT_RECOVERY_LOGS_DIR }}/rollup.log &
          PID1=$!
          
          zk_supervisor test recovery --snapshot --no-deps --ignore-prerequisites --verbose --chain validium &> ${{ env.SNAPSHOT_RECOVERY_LOGS_DIR }}//validium.log &
          PID2=$!
          
          zk_supervisor test recovery --snapshot --no-deps --ignore-prerequisites --verbose --chain custom_token &> ${{ env.SNAPSHOT_RECOVERY_LOGS_DIR }}//custom_token.log &
          PID3=$!

          wait $PID1
          wait $PID2
          wait $PID3

      - name: Run recovery tests (from genesis)
        run: |
          zk_supervisor test recovery --no-deps --no-kill --ignore-prerequisites --verbose --chain era &> ${{ env.GENESIS_RECOVERY_LOGS_DIR }}/rollup.log &
          PID1=$!

          zk_supervisor test recovery --no-deps --no-kill --ignore-prerequisites --verbose --chain validium &> ${{ env.GENESIS_RECOVERY_LOGS_DIR }}/validium.log &
          PID2=$!

          zk_supervisor test recovery --no-deps --no-kill --ignore-prerequisites --verbose --chain custom_token &> ${{ env.GENESIS_RECOVERY_LOGS_DIR }}/custom_token.log &
          PID3=$!

          wait $PID1
          wait $PID2
          wait $PID3

      - name: Run external node server
        run: |
          zk_inception external-node run --ignore-prerequisites --chain era &> ${{ env.EXTERNAL_NODE_LOGS_DIR }}/rollup.log &
          zk_inception external-node run --ignore-prerequisites --chain validium &> ${{ env.EXTERNAL_NODE_LOGS_DIR }}/validium.log &
          zk_inception external-node run --ignore-prerequisites --chain custom_token &> ${{ env.EXTERNAL_NODE_LOGS_DIR }}/custom_token.log &
          sleep 5

      - name: Run integration tests en
        run: |
          zk_supervisor test integration --no-deps --ignore-prerequisites --external-node --chain era &> ${{ env.INTEGRATION_TESTS_EN_LOGS_DIR }}/rollup.log &
          PID1=$!

          zk_supervisor test integration --no-deps --ignore-prerequisites --external-node --chain validium &> ${{ env.INTEGRATION_TESTS_EN_LOGS_DIR }}/validium.log &
          PID2=$!

          zk_supervisor test integration --no-deps --ignore-prerequisites --external-node --chain custom_token &> ${{ env.INTEGRATION_TESTS_EN_LOGS_DIR }}/custom_token.log &
          PID3=$!

          wait $PID1
          wait $PID2
          wait $PID3

      - name: Run revert tests
        run: |
          killall -INT zksync_server || true
          killall -INT zksync_external_node || true
          
          zk_supervisor test revert --no-deps --external-node --no-kill --ignore-prerequisites --chain era &> ${{ env.REVERT_LOGS_DIR }}/rollup.log &
          PID1=$!

          zk_supervisor test revert --no-deps --external-node --no-kill --ignore-prerequisites --chain validium &> ${{ env.REVERT_LOGS_DIR }}/validium.log &
          PID2=$!

          zk_supervisor test revert --no-deps --external-node --no-kill --ignore-prerequisites --chain custom_token &> ${{ env.REVERT_LOGS_DIR }}/custom_token.log &
          PID3=$!
          
          wait $PID1
          wait $PID2
          wait $PID3


      # Upgrade tests should run last, because as soon as they
      # finish the bootloader will be different
      # TODO make upgrade tests safe to run multiple times
      - name: Run upgrade test
        run: |
          zk_supervisor test upgrade --no-deps --chain era


      - name: Upload logs
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: always()
        with:
          name: logs
          path: logs
